version: '4'
services:
  postgres:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_DB: CarScharing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data