server:
  port: 8087

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/CarScharing
    username: postgres
    password: changeme

  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/callback
    baseline-on-migrate: true

  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl.auto: false
        show_sql: true
        format_sql: true
        default_schema: "project"
  jackson:
    serialization:
      fail-on-empty-beans: false
